apiVersion: v1
kind: Service
metadata:
  labels:
    app: svc-oauth2-proxy
  name: svc-oauth2-proxy
spec:
  ports:
  - port: 4180
    protocol: TCP
    targetPort: 4180
  selector:
    app: oauth2-proxy
  type: NodePort
